default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
  - repo: https://github.com/fluxninja/pre-commit-hooks.git
    rev: v0.0.2-rc.6
    hooks:
      - id: circleci-validate