version: 2.1

executors:
  base-cimg-executor:
    docker:
      - image: cimg/base:2022.07


jobs:
  build:
    executor: base-cimg-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test base image
          command: |
            ls -l
            docker version
            cat /etc/lsb-release
      - run:
          name: Run update command
          command: |
            sudo apt-get update  && apt-get install -y --no-install-recommends python3 python3-pip curl neovim  && rm -rf /var/lib/apt/lists/*
  # build:
  #   docker:
  #     - image: python:3.6.3-jessie

  #   #working_directory: /tmp
  #   steps:
  #     - checkout
  #     # - run:
  #     #     name: Creating Dummy Artifacts
  #     #     working_directory: /tmp
  #     #     command: |
  #     #       echo "my artifact file" > /tmp/artifact-1;
  #     #       mkdir /tmp/artifacts;
  #     #       echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
  #     - run:
  #         name: "running requirements.txt file"
  #         command: |
  #           pip install -r requirements.txt
  #     - run:
  #         name: Running python script
  #         #working_directory: /tmp
  #         command: |
  #           echo "Running python make file"
  #           ls -al
  #           mkdir /tmp/artifacts
  #           make run-python-code > /tmp/artifacts/python-test

  #     - store_artifacts:
  #         path: /tmp/artifacts
          #destination: python-test-file
          

      # - store_artifacts:
      #     path: /tmp/artifact-1
      #     destination: artifact-file

      # - store_artifacts:
      #     path: /tmp/artifacts
      #     destination: sachin
  