version: 2.1
jobs:
  build:
    docker:
      - image: python:3.6.3-jessie

    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - run:
          name: Running python script
          command: | 
            echo "Running python make file"
            make run-python-code > /tmp/artifacts/python-test

      - store_artifacts:
          path: /tmp/artifacts
          destination: python-test-file
          

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
          destination: sachin