version: 2.1

orbs:
  eddiewebb/queue: eddiewebb/queue@1.12.0 
executors:
  base-cimg-executor:
    docker:
      - image: cimg/base:2022.07


jobs:
  test-job:
    executor: base-cimg-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test base image
          command: |
            ls -l
            docker version
            cat /etc/lsb-release
  
  update-env: 
    executor: base-cimg-executor
    steps:
      - checkout
      - run:
          name: Update Env 
          command: | 
            echo "Update Env"
  
  block-orb-test:
    executor: base-cimg-executor
    steps:
      - checkout
      - eddiewebb/queue/lock:
          resource-name: my-resource
      - run:
          name: block-orb-test
          command: | 
            echo "Update block-orb-test"
            # start time
            date +"%H:%M:%S"

            # sleep for 5 seconds
            sleep 120

            # end time
            date +"%H:%M:%S"
      - eddiewebb/queue/unlock:
          resource-name: my-resource


workflows:
  version: 2

  first-test:
    jobs:
      - eddiewebb/queue/enqueue:
          name: block-orb-test-workflow
          concurrency:
            group: my-group
            limit: 1
      - eddiewebb/queue/wait-for:
          name: wait-for-previous-job
          requires:
            - block-orb-test-workflow
      - eddiewebb/queue/enqueue:
          name: run-terragrunt
          requires:
            - wait-for-previous-job
          concurrency:
            group: my-group
            limit: 1

      # - block-orb-test:
      #     name:  Test for block-orb
      # - test-job:
      #     name: workflow-test-job 
      # - update-env:
      #     # filters:
      #     #   branches:
      #     #     only:
      #     #       - main
      #     requires:
      #       - "workflow-test-job"
      #     name: update-env-flow 
  




  # build:
  #   docker:
  #     - image: python:3.6.3-jessie

  #   #working_directory: /tmp
  #   steps:
  #     - checkout
  #     # - run:
  #     #     name: Creating Dummy Artifacts
  #     #     working_directory: /tmp
  #     #     command: |
  #     #       echo "my artifact file" > /tmp/artifact-1;
  #     #       mkdir /tmp/artifacts;
  #     #       echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
  #     - run:
  #         name: "running requirements.txt file"
  #         command: |
  #           pip install -r requirements.txt
  #     - run:
  #         name: Running python script
  #         #working_directory: /tmp
  #         command: |
  #           echo "Running python make file"
  #           ls -al
  #           mkdir /tmp/artifacts
  #           make run-python-code > /tmp/artifacts/python-test

  #     - store_artifacts:
  #         path: /tmp/artifacts
          #destination: python-test-file
          

      # - store_artifacts:
      #     path: /tmp/artifact-1
      #     destination: artifact-file

      # - store_artifacts:
      #     path: /tmp/artifacts
      #     destination: sachin
  